### ISSUE TITLE
Would you please add LICENSE

### ISSUE THREAD

**Issue by hituzi-no-sippo** [alex-e-leon/self-referenced-object#1]
@alex-e-leon 
I would like to change the code of this repository and distribute it on github as another repository. However, copyright and LICENSE are not written, would you please add them?

**Comment by alex-e-leon** [comment]
Hi @hitsuji-no-shippo, sure thing.
But can I ask what feature/features you're looking to add in your fork? Maybe one of us can add the feature to this library and publish a new version?

**Comment by hituzi-no-sippo** [comment]
Hi @alex-e-leon.
Thank you for add license. I'm study English, so I'm sorry if it's hard to read.

Refactoring to make it easier for me to read is why I make another repository.
The following features will be added after refactoring.
## Features

-  Add `-` to pattern of replace argument.
https://github.com/alex-e-leon/self-referenced-object/blob/09042272333339e3d20bc5ad5b97b2d22329ad6d/index.js#L35
-  Save parsed value. if parse the same value, use the saved value.
-  If no self property reference is found, throw is not returned and ignored. Ignore is controlled by the argument of `sro`.
https://github.com/alex-e-leon/self-referenced-object/blob/09042272333339e3d20bc5ad5b97b2d22329ad6d/index.js#L4

> Maybe one of us can add the feature to this library and publish a new version?

If you are OK with refactored code.

**Comment by alex-e-leon** [comment]
@hitsuji-no-shippo - that sounds great!

Re: features 1 and 2, I agree, those are good improvements.

Re: feature 3 - ie adding an ignore option to not throw, can I ask why you think that would be useful? In my head I can't think of a good reason for why you'd want that error to be ignored - and if you really did, wouldn't you just wrap the function in `try ... catch ...`?

Maybe I'm missing a good reason though.

If you are happy to provide those features though, I will happily include them and release them in a new version!

**Comment by hituzi-no-sippo** [comment]
@alex-e-leon 
>  if you really did, wouldn't you just wrap the function in try ... catch ...?

I forgot about `try ... catch ...`. Consider whether `try ... cathc ...` is enough.

Feat 1 and 2 are forked and implemented. A pull request will be sent by 18th.
